apiVersion: v1
kind: Service
metadata:
  name: athena-api
  namespace: athena
  labels:
    app.kubernetes.io/name: athena
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: athena
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
